version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo `pwd`
      - cp -R hello_world/ output/
      - pip install -r ./hello_world/requirements.txt -t output
      - echo `python --version` 
  build:
    commands:
      - echo `python --version`
      - aws cloudformation package --template-file template.yaml --s3-bucket aptusrocker23 --output-template-file packaged.yaml
  post_build:
    commands:
      - python ./tests/unit/test_manual.py
artifacts:
  base_directory: output
  type: zip
  files:
    - packaged.yaml
    - "**/*"
