version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo `pwd`
      # - sam build
      - pip install -r ./hello_world/requirements.txt -t ./hello_world/packages/
      - echo `python --version`
  build:
    commands:
      # - sam build
      - aws cloudformation package --template-file template.yaml --s3-bucket aptusrocker23 --output-template-file packaged.yaml
  post_build:
    commands:
      - python ./tests/unit/test_manual.py
artifacts:
  type: zip
  files:
    - packaged.yaml
    - "**/*"
