version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install aws-sam-cli
      - echo `sam --version`
      - sam build      
      - sam package --template-file template.yaml --s3-bucket aptusrocker23 --output-template-file packaged.yaml
  build:
    commands:
      - echo `python --version`
  post_build:
    commands:
      - python ./tests/unit/test_manual.py
artifacts:
  type: zip
  files:
    - template.yaml
    - packaged.yaml
