version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket aptusrocker23 --output-template-file packaged.yaml
  pre_build:
    commands:
      - pip install -r ./requirements.txt
      - python ./tests/unit/test_manual.py
  build:
    commands:
      - echo python --version

artifacts:
  type: zip
  files:
    - template.yaml
    - packaged.yaml
