version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket aptusrocker23 --output-template-file packaged.yaml
  pre_build:
    commands:
      - pip install -r ./hello_world/requirements.txt
  build:
    commands:
      - echo python --version
  post_build:
    commands:
      - python ./tests/unit/test_manual.py
artifacts:
  type: zip
  files:
    - template.yaml
    - packaged.yaml
