version: 0.1
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket aptusrocker23 --output-template-file packaged.yaml
  build:
    commands:
      - echo python --version

artifacts:
  type: zip
  files:
    - template.yaml
    - packaged.yaml