AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
      AutoPublishAlias: live

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: s3://aptusrocker23/705448dcf34adb5718894e4d9274da62
      Handler: app.lambda_handler
      Runtime: python3.7!Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorls3://aptusrocker23/705448dcf34adb5718894e4d9274da62
      Handler: app.lambda_handler
      Runtime: python3.7dFunction:
    Descrips3://aptusrocker23/705448dcf34adb5718894e4d9274da62
      Handler: app.lambda_handler
      Runtime: python3.7tion: "Hello World Lambda Function ARN"
    Value: s3://aptusrocker23/705448dcf34adb5718894e4d9274da62
      Handler: app.lambda_handler
      Runtime: python3.7!GetAtt HelloWorldFunction.Arn
  HelloWorls3://aptusrocker23/705448dcf34adb5718894e4d9274da62
      Handler: app.lambda_handler
      Runtime: python3.7dFunctionIamRole:
    Descrips3://aptusrocker23/705448dcf34adb5718894e4d9274da62
      Handler: app.lambda_handler
      Runtime: python3.7tion: "Implicit IAM Role created for Hello World function"
    Value: s3://aptusrocker23/705448dcf34adb5718894e4d9274da62
      Handler: app.lambda_handler
      Runtime: python3.7!GetAtt HelloWorldFunctionRole.Arn
